uapi dm-log-userspace.h: use __u32, __s32, __u64 and __s64 from linux/types.h
Fixes userspace compilation errors like:

linux/dm-log-userspace.h:416:2: error: unknown type name ‘uint64_t’

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
Reviewed-by: Bart Van Assche <Bart.VanAssche@sandisk.com>
Signed-off-by: Mike Snitzer <snitzer@redhat.com>
(cherry picked from commit 209e2367917317d51732473627ac38e730340b45)