redhat: restore the ability to use %kernel_variant_files
The el8 specific "fix" to disable %kernel_meta_package caused the lack
of %package definitions, which resulted in errors like:

error: line 4295: %files 64k
: package kernel-64k does not exist

Fix this be avoiding expansion of: %%files %{3}
as part of %kernel_variant_files if "%{?dist}" == ".el8"

Fixes: 47e7ce6953d37 ("redhat: various "fixes" to allow building ARK kernel on EL8 buildhost")
Signed-off-by: Mike Snitzer <snitzer@hammerspace.com>